<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Test Cron sous %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Documentation') ?></h3>
            </div>
            <div class="panel-body">
                <p>Cette Application un simple test qui permet de creer un cron sous linux ainsi qu'un formulaire pour afficher le contenu de fichier generé,pour cela il faut suivie ces points suivantes:</p>
                <p>1 - j'ai creé une commande console pour generer un cron en utilisant le zend_console tapez cette commande sur le terminal linux :<label class='zf-green'>php public/index.php crontabcreate</label> </p>
                <p>2 - Veulliez Changer le path du fichier timing.txt dans le fichier <label class='zf-green'>module/Application/config/module.config.php</label> sur la ligne tableau console > router > routes > crontabfile > options> path </p>
                <p>3 - Veulliez Donner le droit d'acceés et d'ecriture au fichier timing.txt </p>
                <p>4 - pour afficher le formulaire cliquer sur le menu en haut Form Cron </p>
                
            </div>
        </div>
    </div>
</div>
